/** عناوين عربية للدروس — تُستخدم في تفاصيل التقدم */
export const LESSON_LABELS_AR = {
  "binary-cards": "بطاقات الأرقام الثنائية",
  "binary-puzzle": "ألغاز الأرقام الثنائية",
  "binary-matching": "مطابقة الأرقام الثنائية",
  "number-systems": "أنظمة العد",
  "python-intro": "مقدمة بايثون",
  "string-splitting": "تقسيم النصوص",
  "ascii-unicode": "ASCII و Unicode",
  "hex-puzzle": "لغز الست عشري",
  "hex-colors": "الألوان والست عشري",
  "karnaugh-maps": "خريطة كارنوف",
  "logic-equivalence": "الاقترانات المنطقية",
  "python-tuples": "الحقول المترابطة",
  "nested-loops-lab": "الحلقات المتداخلة",
  "linear-search": "البحث الخطي",
  "binary-search": "البحث الثنائي",
  "sorting-algorithms": "فرز الاختيار",
  "sieve-primes": "غربال إراتوستينس",
  "caesar-cipher": "شفرة قيصر والتشفير",
  "memory-hierarchy": "الذاكرة والتخزين المؤقت",
  "cpu-scheduling": "جدولة المعالج",
  "python-scope": "نطاق المتغيرات (Scope)",
  "dice-random": "رمي النرد والعشوائية",
  "tic-tac-toe": "تيك-تاك-تو",
  "game-planning": "تخطيط اللعبة",
  "fibonacci-sequence": "متتالية فيبوناتشي",
  "algorithm-complexity": "تعقيد الخوارزميات (Big-O)",
  "tower-of-hanoi": "برج هانوي",
  "python-files-io": "الملفات في بايثون",
  "python-recursion": "الاستدعاء الذاتي",
  "fractals-intro": "الكسوريات والتشابه الذاتي",
  "koch-snowflake": "ندفة Koch",
  "sierpinski-triangle": "مثلث Sierpinski",
  "oop-foundations": "البرمجة كائنية التوجه",
  "steganography-python": "إخفاء المعلومات",
  "fractal-tree-recursion": "الشجرة المتكررة",
  "locker-pascal-problem": "مشكلة الخزانة ومثلث باسكال",
};

export function lessonLabelAr(lessonId) {
  return LESSON_LABELS_AR[lessonId] || lessonId;
}
