/** إجابات المعلم — اليوم الثاني (مفتاح PDF كامل) */
export const day02TeacherAnswers = {
  titleAr: "إجابات المعلم — اليوم الثاني",
  sections: [
    {
      id: "warmup",
      titleAr: "النشاط التمهيدي — تحويلات و ASCII",
      pdfPageIndex: 93,
      lessonRoute: "/lessons/conversions-intro",
      items: [
        {
          q: "1010₂ → عشري",
          a: "10",
          steps: ["8+2=10"],
          teachingNotes: "راجع القيمة المكانية قبل الجمع في الأنظمة.",
          expectedErrors: ["نسيان 2⁰", "ترتيب البits معكوس"],
          feedback: "حوّل عكسياً للتحقق.",
        },
        {
          q: "ASCII('M')",
          a: "77 (0x4D)",
          steps: ["M=77₁₀"],
          teachingNotes: "اربط ASCII بالتمثيل الثنائي/hex.",
          expectedErrors: ["خلط M مع m"],
          feedback: "جدول ASCII أو محوّل المنصة.",
        },
      ],
    },
    {
      id: "base-arith",
      titleAr: "الحساب في الأنظمة",
      pdfPageIndex: 101,
      lessonRoute: "/lessons/base-arithmetic",
      items: [
        {
          q: "1011₂ + 1101₂",
          a: "11000₂ = 24₁₀",
          steps: ["1+1=0 c1", "1+0+1=0 c1", "0+1+1=0 c1", "1+1+1=1", "تحقق: 11+13=24"],
          teachingNotes: "ألزم التحقق العشري.",
          expectedErrors: ["نسيان carry", "محاذاة خاطئة"],
          feedback: "carry chain من اليمين.",
        },
        {
          q: "23₅ + 14₅",
          a: "42₅ (22₁₀)",
          steps: ["3+4=7→2 c1", "2+1+1=4"],
          teachingNotes: "الأساس 5 يثبت القاعدة العامة.",
          expectedErrors: ["carry كأنه binary"],
          feedback: "sum mod 5.",
        },
        {
          q: "A3₁₆ + 5D₁₆",
          a: "100₁₆",
          steps: ["3+D=16→0 c1", "A+5+1=16→0 c1", "1"],
          teachingNotes: "hex carry عند ≥16.",
          expectedErrors: ["digit > F"],
          feedback: "تحويل hex→dec.",
        },
      ],
    },
    {
      id: "twos",
      titleAr: "مكمل العدد 2",
      pdfPageIndex: 104,
      lessonRoute: "/lessons/twos-complement",
      items: [
        {
          q: "−5 في 8-bit",
          a: "11111011",
          steps: ["00000101", "flip", "+1"],
          teachingNotes: "MSB=1 للسالب.",
          expectedErrors: ["flip دون +1"],
          feedback: "TwosComplementLab.",
        },
        {
          q: "7−3 في 8-bit",
          a: "00000100 (4)",
          steps: ["7 + twos(−3)", "تجاهل carry بعد 8 bits"],
          teachingNotes: "الطرح = جمع مكمل.",
          expectedErrors: ["overflow غير مفهوم"],
          feedback: "قصّ n bits.",
        },
      ],
    },
    {
      id: "float",
      titleAr: "الفاصلة العائمة",
      pdfPageIndex: 106,
      lessonRoute: "/lessons/floating-point",
      items: [
        {
          q: "0.1+0.2==0.3?",
          a: "False",
          steps: ["تقريب ثنائي", "استخدم epsilon"],
          teachingNotes: "لا تعاقب — وضّح التمثيل.",
          expectedErrors: ["اعتقاد خطأ برمجي"],
          feedback: "abs(a-b)<1e-9.",
        },
      ],
    },
    {
      id: "algo",
      titleAr: "الخوارزميات",
      pdfPageIndex: 110,
      lessonRoute: "/lessons/algorithms",
      items: [
        {
          q: "ترتيب: أكبر عددين",
          a: "اقرأ → compare → print",
          steps: ["READ a,b", "IF a>b max=a ELSE max=b", "PRINT max"],
          teachingNotes: "AlgorithmStepsLab + card sort.",
          expectedErrors: ["print قبل read"],
          feedback: "trace table.",
        },
      ],
    },
    {
      id: "if",
      titleAr: "If",
      pdfPageIndex: 147,
      lessonRoute: "/lessons/if-statement",
      items: [
        {
          q: "score=55, >=50",
          a: "ناجح / Pass",
          steps: ["55>=50 True", "if body"],
          teachingNotes: "== vs =.",
          expectedErrors: ["IndentationError", "x=5 in if"],
          feedback: "IfStatementLab.",
        },
        {
          q: "d1=4,d2=6",
          a: "2 (elif)",
          steps: ["4<6", "elif branch"],
          teachingNotes: "elif ترتيب من الأعلى.",
          expectedErrors: ["else قبل elif"],
          feedback: "trace.",
        },
      ],
    },
    {
      id: "lab",
      titleAr: "مختبر الحاسب",
      pdfPageIndex: 149,
      lessonRoute: "/lessons/day02-computer-lab",
      items: [
        {
          q: "sum 1..10",
          a: "55",
          steps: ["for i in range(1,11): s+=i"],
          teachingNotes: "حفظ التقدم عبر API.",
          expectedErrors: ["range(10) off-by-one"],
          feedback: "Day02ComputerLabPanel.",
        },
        {
          q: "while 5→1",
          a: "5 lines output",
          steps: ["n=5 while n>0: print(n); n-=1"],
          teachingNotes: "تحديث شرط while.",
          expectedErrors: ["infinite loop"],
          feedback: "n-=1.",
        },
      ],
    },
  ],
};
