/** إجابات المعلم — اليوم الثالث (مفتاح PDF كامل) */
export const day03TeacherAnswers = {
  titleAr: "إجابات المعلم — اليوم الثالث",
  teacherGuidance: {
    titleAr: "إرشادات تدريس اليوم الثالث — نظرة شاملة",
    pdfPageIndex: 169,
    overviewAr:
      "اليوم الثالث يربط برمجة بايثون (ثوابت، مصفوفات 2D، تحكم الحلقات) بأنشطة عددية (مقسومات، Collatz) ثم ينتقل إلى المنطق الرقمي (جداول الحقيقة والبوابات). ابدأ بالبرمجة صباحاً واترك المنطق بعد الاستراحة.",
    pacingAr:
      "≈45 دقيقة برمجة (152–158) → 25 دقيقة أنشطة (170–173) → 40 دقيقة منطق (158–168). لا تتخطَّ Collatz إن تأخر الوقت — قصِّ المنطق بدلاً من الأنشطة.",
    sequenceAr: [
      "1) ثوابت → 2D arrays → break/continue/pass/else",
      "2) نشاط المقسومات (تطبيق break)",
      "3) Collatz ثم نشاط الأرقام والخطوات (تمييز القواعد)",
      "4) جداول الحقيقة (مرجع + اشتقاق + إجابات) → البوابات",
    ],
    materialsAr:
      "أوراق PDF 158–159 (مرجع الحقيقة)، 163–164 (مرجع البوابات)، أقلام، لوح. محاكاة المنصة: TruthTableBuilder و LogicGates.",
    assessmentAr:
      "تحقق سريع: m[1][1]، continue يتخطى i=2، مقسومات 12، خطوات Collatz لـ n=6، صف AND=11، AND(1,0)=0.",
  },
  sections: [
    {
      id: "constants",
      titleAr: "الثوابت في بايثون",
      pdfPageIndex: 152,
      lessonRoute: "/lessons/python-constants",
      items: [
        {
          q: "PI = 3.14 ثم PI = 4 — ماذا يحدث؟",
          a: "لا خطأ syntax — لكن مخالف لاتفاق الثوابت؛ القارئ يتوقع PI ثابتاً.",
          steps: ["PI = 3.14", "PI = 4 — مسموح تقنياً", "الاسم UPPER_CASE يدل على «لا تغيّر»"],
          teachingNotes: "بايثون لا تمنع إعادة التعيين — الاتفاق هو PEP8. قارن score (متغير) مع MAX_SCORE (ثابت).",
          expectedErrors: ["اعتقاد SyntaxError", "كتابة pi بدل PI", "خلط ثابت مع literal"],
          feedback: "ConstantsLesson + IfStatementLab للمقارنة.",
        },
        {
          q: "MAX_SCORE = 100, score = 85 — score <= MAX_SCORE؟",
          a: "True",
          steps: ["85 <= 100", "True"],
          teachingNotes: "استخدم الثابت في الشرط — نموذج واقعي للدرجات.",
          expectedErrors: ["MAX_SCORE = score", "== بدل = في التعيين"],
          feedback: "اطلب من الطلاب تعريف ثابت GRAVITY=9.8 واستخدامه.",
        },
        {
          q: "DAYS_IN_WEEK = 7 — ثابت أم متغير؟",
          a: "ثابت (اتفاقياً) — UPPER_CASE + قيمة منطقية لا تتغير أثناء التشغيل.",
          steps: ["اسم UPPER_CASE", "7 لا يتغير في البرنامج", "x = 5 متغير لأنه قد يُعدَّل"],
          teachingNotes: "ناقش: أي أسماء في برنامجهم ثابتة؟ (PI، MAX_ATTEMPTS، …).",
          expectedErrors: ["كل assignment = ثابت", "رفض float كثابت"],
          feedback: "guidedPractice g1/g2 في الدرس.",
        },
      ],
    },
    {
      id: "multi-dim",
      titleAr: "المصفوفات متعددة الأبعاد",
      pdfPageIndex: 154,
      lessonRoute: "/lessons/python-multi-arrays",
      items: [
        {
          q: "m = [[1,2],[3,4]] — m[0][1]؟",
          a: "2",
          steps: ["m[0] = [1,2]", "m[0][1] = العنصر الثاني في الصف الأول", "2"],
          teachingNotes: "ارسم الجدول: صف = row (فهرس أول)، عمود = col (فهرس ثاني).",
          expectedErrors: ["m[1][0]=2 (عكس الفهرس)", "m[0,1] syntax"],
          feedback: "interactiveExample في الدرس.",
        },
        {
          q: "len([[1,2],[3,4]]) — عدد الصفوف؟",
          a: "2",
          steps: ["مصفوفة = قائمة قوائم", "صفان: [1,2] و [3,4]", "len = 2"],
          teachingNotes: "len تعطي عدد الصفوف لا العناصر الكلية.",
          expectedErrors: ["4 (عد العناصر)", "len(m[0]) للصفوف"],
          feedback: "guidedPractice g2.",
        },
        {
          q: "m[0][1] = 9 — النتيجة؟",
          a: "[[1,9],[3,4]]",
          steps: ["الوصول: صف 0 عمود 1", "تعيين 9", "الصف الأول يصبح [1,9]"],
          teachingNotes: "التعديل in-place — لا نسخ جديد.",
          expectedErrors: ["m[1][1]=9", "محاولة m[0]=9"],
          feedback: "workedExample e2 + nested for loop.",
        },
      ],
    },
    {
      id: "break-continue",
      titleAr: "break / continue / pass / else",
      pdfPageIndex: 156,
      lessonRoute: "/lessons/python-break-continue",
      items: [
        {
          q: "for i in range(5): if i==2: continue; print(i) — المخرجات؟",
          a: "0, 1, 3, 4 (بدون 2)",
          steps: ["i=0,1 → print", "i=2 → continue يتخطى print", "i=3,4 → print"],
          teachingNotes: "continue = انتقل للتكرار التالي دون إنهاء الحلقة.",
          expectedErrors: ["break بدل continue", "print(2) يظهر", "IndentationError"],
          feedback: "interactiveExample + BreakContinuePassLab.",
        },
        {
          q: "for i in range(10): if i==5: break; print(i) — كم سطر؟",
          a: "5 أسطر (0–4)",
          steps: ["i=0..4 → print", "i=5 → break", "لا print بعد 5"],
          teachingNotes: "break = خروج فوري من الحلقة.",
          expectedErrors: ["10 أسطر", "break يطبع 5"],
          feedback: "workedExample e1.",
        },
        {
          q: "for i in range(3): pass — else: print('done') — يُطبع done؟",
          a: "نعم — else تُنفَّذ لأن الحلقة اكتملت دون break.",
          steps: ["for i=0,1,2 — pass لا شيء", "لا break", "else: print('done')"],
          teachingNotes: "else مع for/while = «اكتملت دون break». مفاجأة شائعة للطلاب.",
          expectedErrors: ["else لا تُنفَّذ", "ربط else بـ if لا for", "SyntaxError عند pass"],
          feedback: "independentPractice i2 + مثال break قبل else.",
        },
      ],
    },
    {
      id: "divisors",
      titleAr: "نشاط المقسومات",
      pdfPageIndex: 170,
      lessonRoute: "/lessons/divisors-activity",
      items: [
        {
          q: "n=12 — اذكر كل المقسومات",
          a: "1, 2, 3, 4, 6, 12",
          steps: ["for i in 1..12", "12%1=0 → 1", "…", "12%12=0 → 12", "6 مقسومات"],
          teachingNotes: "1 و n دائماً مقسومان. ربط n%i==0 بالقابلية للقسمة.",
          expectedErrors: ["نسيان 1 أو 12", "إدراج 5 (12%5≠0)", "break مبكر"],
          feedback: "DivisorsLab — تحقق: 6×2=12.",
        },
        {
          q: "n=12 — هل 12 أولي؟ (باستخدام break)",
          a: "لا — break عند أول مقسوم غير 1 و n (مثلاً i=2).",
          steps: ["for i in 2..11", "12%2==0 → ليس أولياً", "break"],
          teachingNotes: "امتداد النشاط: break عند found divisor.",
          expectedErrors: ["فحص حتى n", "اعتبار 12 أولياً"],
          feedback: "reflectionAr في activityGuide.",
        },
        {
          q: "n=7 — عدد المقسومات؟",
          a: "2 (1 و 7 فقط — أولي)",
          steps: ["7%2≠0", "7%3≠0", "…", "1,7 فقط"],
          teachingNotes: "قارن 12 (مركب) مع 7 (أولي) على اللوح.",
          expectedErrors: ["3 مقسومات", "7 مقسوم"],
          feedback: "DivisorsLab مع n=7.",
        },
      ],
    },
    {
      id: "numbers-steps",
      titleAr: "نشاط الأرقام والخطوات",
      pdfPageIndex: 173,
      lessonRoute: "/lessons/numbers-steps-activity",
      items: [
        {
          q: "n=8 — كم خطوة للوصول إلى 0؟ (عدّ تنازلي: n←n−1)",
          a: "8 خطوات",
          steps: ["8→7→6→5→4→3→2→1→0", "كل طرح = خطوة", "8 خطوات"],
          teachingNotes: "ليس Collatz — هنا طرح 1 فقط. NumbersStepsLab ≠ CollatzSimulator.",
          expectedErrors: ["خلط مع Collatz (3n+1)", "7 خطوات (نسيان 0)", "n خطوات ≠ n−1"],
          feedback: "NumbersStepsLab — verificationAr: آخر قيمة 0 وعداد = n.",
        },
        {
          q: "n=5 — جدول التتبّع (n قبل → n بعد)",
          a: "5→4→3→2→1→0 — 5 خطوات",
          steps: ["step0: n=5", "step1: n=4", "…", "step5: n=0"],
          teachingNotes: "جدول الأعمدة: #، n، عملية، steps — يصحح off-by-one.",
          expectedErrors: ["4 خطوات", "تطبيق قواعد Collatz"],
          feedback: "deepSection vs-collatz في الدرس.",
        },
        {
          q: "while n>0: n-=1; steps+=1 — n=1 ينتج؟",
          a: "1 خطوة (1→0)",
          steps: ["n=1, steps=0", "n>0 → n=0, steps=1", "n=0 → توقف"],
          teachingNotes: "while مناسب هنا — عدد التكرارات غير معروف مسبقاً بخلاف for ثابت.",
          expectedErrors: ["0 خطوات", "حلقة لا نهائية (نسيان n-=1)"],
          feedback: "reflectionAr: متى while بدل for؟",
        },
      ],
    },
    {
      id: "collatz",
      titleAr: "تخمين Collatz",
      pdfPageIndex: 172,
      lessonRoute: "/lessons/collatz",
      items: [
        {
          q: "n=6 — عدد الخطوات حتى 1؟",
          a: "8",
          steps: ["6→3 (÷2)", "3→10 (3n+1)", "10→5→16→8→4→2→1", "8 تحويلات"],
          teachingNotes: "زوج: n//=2. فرد: n=3*n+1. استخدم // لا /.",
          expectedErrors: ["7 أو 9 خطوات", "float بدل int", "while بدون تحديث n"],
          feedback: "CollatzSimulator — trace table.",
        },
        {
          q: "n=4 — أول خطوتان؟",
          a: "4→2→1",
          steps: ["4 زوج → 2", "2 زوج → 1", "خطوتان"],
          teachingNotes: "سلسلة قصيرة للتحقق السريع من القواعد.",
          expectedErrors: ["4→12 (3n+1)", "4→2→4 (حلقة)"],
          feedback: "guidedPractice g1.",
        },
        {
          q: "n=3 — أول خطوة؟",
          a: "10 (3×3+1)",
          steps: ["3 فرد", "3*3+1=10"],
          teachingNotes: "الفرد يكبر الرقم أحياناً — هذا طبيعي في Collatz.",
          expectedErrors: ["3→1 (÷2)", "9 بدل 10"],
          feedback: "guidedPractice g2 + quickCheck.",
        },
      ],
    },
    {
      id: "truth-tables",
      titleAr: "جداول الحقيقة — مرجع واشتقاق وإجابات",
      pdfPageIndex: 158,
      lessonRoute: "/lessons/truth-tables",
      items: [
        {
          q: "مرجع PDF ص 158–159 — A AND B (صفوف 00,01,10,11)",
          a: "0001 — الناتج 1 فقط عند A=1,B=1",
          steps: ["00→0", "01→0", "10→0", "11→1"],
          teachingNotes: "وزّع ورقة المرجع — رموز ∧ ∨ ¬. 4 صفوف لمتغيرين.",
          expectedErrors: ["0111 (خلط AND/OR)", "صف ناقص", "ترتيب صفوف خاطئ"],
          feedback: "TruthTableBuilder + /simulations#truth.",
        },
        {
          q: "اشتقاق A OR B — املأ عمود الناتج",
          a: "0111",
          steps: ["00→0", "01→1", "10→1", "11→1"],
          teachingNotes: "اشتقاق = طبّق التعبير على كل صف — لا حفظ.",
          expectedErrors: ["0001 (AND)", "1111 (OR مع NOT)"],
          feedback: "deepSection derive + workedExample e2.",
        },
        {
          q: "إجابات PDF ص 162 — A XOR B عند A=1,B=0؟",
          a: "1",
          steps: ["XOR = مختلفان", "1≠0 → 1"],
          teachingNotes: "XOR: 1 إذا أحدهما فقط 1. جدول كامل: 0110.",
          expectedErrors: ["0 (AND)", "1 AND 0=0"],
          feedback: "truth-answers — teacher-only section.",
        },
        {
          q: "NOT A — عمود A في ترتيب 00,01,10,11",
          a: "1010",
          steps: ["A=0→NOT=1", "A=0→1", "A=1→0", "A=1→0"],
          teachingNotes: "NOT يعكس bit واحد — مدخل واحد.",
          expectedErrors: ["0101 (عكس B)", "NOT(A AND B)"],
          feedback: "guidedPractice g1: NOT 1 = 0.",
        },
      ],
    },
    {
      id: "logic-gates",
      titleAr: "البوابات المنطقية — مرجع وإجابات",
      pdfPageIndex: 163,
      lessonRoute: "/lessons/logic-gates",
      items: [
        {
          q: "مرجع PDF ص 163–164 — رمز AND ومدخلاتها",
          a: "مدخلان — الناتج 1 فقط إذا كلاهما 1",
          steps: ["AND = &", "1,1→1", "أي 0→0"],
          teachingNotes: "اربط البوابة بعمود جدول الحقيقة — نفس القواعد.",
          expectedErrors: ["AND = OR", "NOT يأخذ مدخلين"],
          feedback: "LogicGates lesson deepSections.",
        },
        {
          q: "AND(1,0) — الناتج؟",
          a: "0",
          steps: ["1 AND 0", "ليس كلاهما 1", "0"],
          teachingNotes: "مثال سريع قبل المحاكاة.",
          expectedErrors: ["1", "خطأ syntax"],
          feedback: "workedExample e1 + /simulations#gates.",
        },
        {
          q: "NOR(0,0) — إجابات PDF ص 167–168",
          a: "1 (NOT(0 OR 0) = NOT 0 = 1)",
          steps: ["0 OR 0 = 0", "NOT 0 = 1", "1"],
          teachingNotes: "NOR = NOT OR. XOR = مختلفان.",
          expectedErrors: ["0", "1 (OR)", "NOR = NAND"],
          feedback: "gates-answers — independentPractice i2: XOR 1,1=0.",
        },
        {
          q: "NOT(1) — الناتج؟",
          a: "0",
          steps: ["NOT يعكس", "1→0"],
          teachingNotes: "NOT بوابة أحادية — لا تخلط مع AND.",
          expectedErrors: ["1", "NOT(1,0)"],
          feedback: "LogicGatesLab + circuit sim.",
        },
      ],
    },
    {
      id: "teacher-guidance",
      titleAr: "إرشادات المعلم — إيقاع وتمايز",
      pdfPageIndex: 169,
      lessonRoute: "/teacher/day-03-answers",
      items: [
        {
          q: "إيقاع الحصة — أين توقف إن نفد الوقت؟",
          a: "أكمل break/continue + مقسومات؛ قصِّ derive المنطق أو اجعله واجباً. لا تتخطَّ Collatz/numbers-steps معاً.",
          steps: ["152–158: أساس (لا تقصّ)", "170–173: أنشطة (15+12 د)", "158–168: منطق (قابل للتقصير)"],
          teachingNotes: "pdf 169–170: إرشادات مطبوعة للمعلم — راجع قبل الحصة.",
          expectedErrors: ["تخطي الأنشطة", "منطق قبل فهم الحلقات"],
          feedback: "teacherGuidance.pacingAr أعلاه.",
        },
        {
          q: "أخطاء صفية شائعة — ماذا تصحح فوراً؟",
          a: "خلط Collatz مع العد التنازلي؛ m[col][row]؛ break vs continue؛ AND vs OR.",
          steps: ["اكتب جدول مقارنة Collatz vs n−1", "ارسم 2×2 matrix", "trace break/continue", "AND/OR side-by-side"],
          teachingNotes: "لا تعاقب — وضّح أن Collatz غير مثبت رياضياً (تخمين).",
          expectedErrors: ["تصحيح صوتي فقط", "تجاهل IndentationError"],
          feedback: "commonMistakes في كل درس.",
        },
        {
          q: "تمايز — دعم متقدم وتأييد",
          a: "متقدم: أولية + Collatz لـ n=27؛ متوسط: DivisorsLab؛ دعم: numbers-steps جدول فقط + truth table جاهز.",
          steps: ["متقدم: is_prime + longest Collatz", "متوسط: labs كاملة", "دعم: جداول مملوءة جزئياً"],
          teachingNotes: "pdf 170: pairs — طالب قوي يساعد بجدول التتبّع لا بالحل.",
          expectedErrors: ["نفس المسألة للجميع", "حل كامل للضعيف"],
          feedback: "NumbersStepsLab hints + CollatzSimulator stepIdx.",
        },
      ],
    },
  ],
};
