/**
 * إجابات نموذجية لأوراق العمل — للمعلم فقط (لا تُرسل للطالب).
 */
export const WORKSHEET_MODEL_ANSWERS = {
  "ws-day-01": {
    teacherDayRoute: "/teacher/day-01-answers",
    tasks: [
      { n: 1, modelAr: "2→10₂، 11→1011₂، 24→11000₂، 50→110010₂، 616→1001101000₂، 22→10110₂" },
      { n: 2, modelAr: "101101→45، 111111→63، 00111011→59، 011010→26" },
      { n: 3, modelAr: "127₁₀" },
      { n: 4, modelAr: "3، 7، 15، 31، 63" },
      { n: 5, modelAr: "12=8+4، 5=4+1، 16=16، 31=16+8+4+2+1" },
      { n: 6, modelAr: "أحمر 16711680، أخضر 65280، أزرق 255؛ أبيض FFFFFF، أسود 000000" },
      { n: 7, modelAr: "ASCII 7-bit؛ Unicode يغطي العربية — مثل «أ» U+0623" },
      { n: 8, modelAr: "ثلاث قواعد من الميثاق + التقويم القبلي تشخيصي" },
    ],
  },
  "ws-day-02": {
    teacherDayRoute: "/teacher/day-02-answers",
    tasks: [
      {
        n: 1,
        modelAr: "1010₂→10، 25₁₀→11001₂، A3₁₆→163₁₀ — مع خطوات التحويل",
        stepsAr: ["قسمة متكررة على 2", "تحقق عكسي"],
      },
      {
        n: 2,
        modelAr: "1011₂+1101₂=11000₂ (24₁₀)؛ 23₅+14₅=42₅",
        stepsAr: ["carry من اليمين", "تحقق عشري"],
      },
      { n: 3, modelAr: "خطوات واضحة ومحددة قابلة للتنفيذ (الخيار أ)." },
      { n: 4, modelAr: "صح — لأن 55 ≥ 50." },
      { n: 5, modelAr: "جيد جداً (الخيار ب)." },
      { n: 6, modelAr: "15" },
      { n: 7, modelAr: "49" },
      { n: 8, modelAr: "صح — بسبب محدودية تمثيل floating-point." },
      { n: 9, modelAr: "توليد تسلسل أعداد للتكرار (الخيار أ)." },
      { n: 10, modelAr: "صح — يمكن استخدام if لاتخاذ قرار." },
    ],
  },
  "ws-day-03": {
    teacherDayRoute: "/teacher/day-03-answers",
    tasks: [
      { n: 1, modelAr: "صح — DAYS_IN_WEEK ثابت اتفاقيًا." },
      { n: 2, modelAr: "3" },
      { n: 3, modelAr: "0,1,3,4 (الخيار ب)." },
      { n: 4, modelAr: "6" },
      { n: 5, modelAr: "خطأ — 12 ليس أوليًا." },
      { n: 6, modelAr: "8" },
      { n: 7, modelAr: "8" },
      { n: 8, modelAr: "1 (الخيار ب)." },
      { n: 9, modelAr: "0111" },
      { n: 10, modelAr: "0" },
    ],
  },
  "ws-day-04": {
    teacherDayRoute: "/teacher/day-04-answers",
    tasks: [
      { n: 1, modelAr: "الخلية 11 فقط (الخيار ج)." },
      { n: 2, modelAr: "صح." },
      { n: 3, modelAr: "(NOT A) OR (NOT B)." },
      { n: 4, modelAr: "A." },
      { n: 5, modelAr: "20" },
      { n: 6, modelAr: "غير مسموح لأن tuple غير قابلة للتعديل (الخيار ب)." },
      { n: 7, modelAr: "a=7, b=8." },
      { n: 8, modelAr: "12" },
      { n: 9, modelAr: "9" },
      { n: 10, modelAr: "0,2,4,6" },
    ],
  },
  "ws-day-05": {
    teacherDayRoute: "/teacher/day-05-answers",
    tasks: [
      { n: 1, modelAr: "4" },
      { n: 2, modelAr: "6" },
      { n: 3, modelAr: "خطأ — يشترط الترتيب." },
      { n: 4, modelAr: "3" },
      { n: 5, modelAr: "1" },
      { n: 6, modelAr: "[1,3,6,8,9]" },
      { n: 7, modelAr: "O(n^2) (الخيار د)." },
      { n: 8, modelAr: "9 (الخيار ج)." },
      { n: 9, modelAr: "خطأ — 1 ليس أوليًا." },
      { n: 10, modelAr: "2، 3، 5، 7، 11، 13، 17، 19، 23، 29." },
    ],
  },
  "ws-day-06": {
    teacherDayRoute: "/teacher/day-06-answers",
    tasks: [
      { n: 1, modelAr: "ECV" },
      { n: 2, modelAr: "Cache (أ)" },
      { n: 3, modelAr: "CPU→تنفيذ؛ RAM→أثناء التشغيل؛ HDD→دائم" },
      { n: 4, modelAr: "انتظار P2 = 2" },
      { n: 5, modelAr: "صح — SRT" },
      { n: 6, modelAr: "أول وصول أول خدمة" },
      { n: 7, modelAr: "A" },
      { n: 8, modelAr: "خطأ — ضعيفة أمنيًا" },
      { n: 9, modelAr: "≈1.67" },
      { n: 10, modelAr: "تخزين أثناء التشغيل" },
    ],
  },
  "ws-day-07": {
    teacherDayRoute: "/teacher/day-07-answers",
    tasks: [
      { n: 1, modelAr: "3" },
      { n: 2, modelAr: "Local (أ)" },
      { n: 3, modelAr: "1–6 شاملاً (أ)" },
      { n: 4, modelAr: "7" },
      { n: 5, modelAr: "متوسط (ب)" },
      { n: 6, modelAr: "9" },
      { n: 7, modelAr: "8" },
      { n: 8, modelAr: "صح" },
      { n: 9, modelAr: "تخطيط القواعد (أ)" },
      { n: 10, modelAr: "صح" },
    ],
  },
  "ws-day-08": {
    teacherDayRoute: "/teacher/day-08-answers",
    tasks: [
      { n: 1, modelAr: "13" },
      { n: 2, modelAr: "n <= 1 (أ)" },
      { n: 3, modelAr: "O(n) (أ)" },
      { n: 4, modelAr: "O(log n) (أ)" },
      { n: 5, modelAr: "7" },
      { n: 6, modelAr: "خطأ" },
      { n: 7, modelAr: "'w' (أ)" },
      { n: 8, modelAr: "3" },
      { n: 9, modelAr: "صح" },
      { n: 10, modelAr: "O(n²) (أ)" },
    ],
  },
  "ws-day-09": {
    teacherDayRoute: "/teacher/day-09-answers",
    tasks: [
      { n: 1, modelAr: "120" },
      { n: 2, modelAr: "إيقاف التكرار (أ)" },
      { n: 3, modelAr: "21" },
      { n: 4, modelAr: "تشابه ذاتي (أ)" },
      { n: 5, modelAr: "12" },
      { n: 6, modelAr: "صح" },
      { n: 7, modelAr: "9" },
      { n: 8, modelAr: "استدعاء ذاتي + turtle (أ)" },
      { n: 9, modelAr: "صح" },
      { n: 10, modelAr: "48" },
    ],
  },
};
