/**
 * إجابات نموذجية لأوراق العمل — للمعلم فقط (لا تُرسل للطالب).
 */
export const WORKSHEET_MODEL_ANSWERS = {
  "ws-day-01": {
    teacherDayRoute: "/teacher/day-01-answers",
    tasks: [
      { n: 1, modelAr: "2→10₂، 11→1011₂، 24→11000₂، 50→110010₂، 616→1001101000₂، 22→10110₂" },
      { n: 2, modelAr: "101101→45، 111111→63، 00111011→59، 011010→26" },
      { n: 3, modelAr: "127₁₀" },
      { n: 4, modelAr: "3، 7، 15، 31، 63" },
      { n: 5, modelAr: "12=8+4، 5=4+1، 16=16، 31=16+8+4+2+1" },
      { n: 6, modelAr: "أحمر 16777215، أخضر 65280، أزرق 255؛ أبيض FFFFFF، أسود 000000" },
      { n: 7, modelAr: "ASCII 7-bit؛ Unicode يغطي العربية — مثل «أ» U+0623" },
      { n: 8, modelAr: "ثلاث قواعد من الميثاق + التقويم القبلي تشخيصي" },
    ],
  },
  "ws-day-02": {
    teacherDayRoute: "/teacher/day-02-answers",
    tasks: [
      {
        n: 1,
        modelAr: "1010₂→10، 25₁₀→11001₂، A3₁₆→163₁₀ — مع خطوات التحويل",
        stepsAr: ["قسمة متكررة على 2", "تحقق عكسي"],
      },
      {
        n: 2,
        modelAr: "1011₂+1101₂=11000₂ (24₁₀)؛ 23₅+14₅=42₅",
        stepsAr: ["carry من اليمين", "تحقق عشري"],
      },
      { n: 3, modelAr: "خوارزمية مرقمة: مدخلات → خطوات → مخرجات (مثل: إعداد شاي)" },
      { n: 4, modelAr: "if grade >= 50: print('نجح') else: print('راسب')" },
      { n: 5, modelAr: "سلسلة elif للتقديرات 90/80/70/50" },
      { n: 6, modelAr: "while i <= n: sum += i; i += 1" },
      { n: 7, modelAr: "for i in range(1, 11): print(i*i)" },
      { n: 8, modelAr: "تمثيل IEEE-754 محدود — 0.1+0.2≈0.30000000000000004" },
      { n: 9, modelAr: "تعريفات: خوارزمية، pseudocode، if، while، for، range، float" },
      { n: 10, modelAr: "مختبر 60 د: برنامج if لرمي حجرين + خوارزمية Collatz مبسطة" },
    ],
  },
  "ws-day-06": {
    teacherDayRoute: "/teacher/day-06-answers",
    tasks: [
      { n: 1, modelAr: "ECV" },
      { n: 2, modelAr: "Cache (أ)" },
      { n: 3, modelAr: "CPU→تنفيذ؛ RAM→أثناء التشغيل؛ HDD→دائم" },
      { n: 4, modelAr: "انتظار P2 = 2" },
      { n: 5, modelAr: "صح — SRT" },
      { n: 6, modelAr: "أول وصول أول خدمة" },
      { n: 7, modelAr: "A" },
      { n: 8, modelAr: "خطأ — ضعيفة أمنيًا" },
      { n: 9, modelAr: "≈1.67" },
      { n: 10, modelAr: "تخزين أثناء التشغيل" },
    ],
  },
  "ws-day-07": {
    teacherDayRoute: "/teacher/day-07-answers",
    tasks: [
      { n: 1, modelAr: "3" },
      { n: 2, modelAr: "Local (أ)" },
      { n: 3, modelAr: "1–6 شاملاً (أ)" },
      { n: 4, modelAr: "7" },
      { n: 5, modelAr: "متوسط (ب)" },
      { n: 6, modelAr: "9" },
      { n: 7, modelAr: "8" },
      { n: 8, modelAr: "صح" },
      { n: 9, modelAr: "تخطيط القواعد (أ)" },
      { n: 10, modelAr: "صح" },
    ],
  },
  "ws-day-08": {
    teacherDayRoute: "/teacher/day-08-answers",
    tasks: [
      { n: 1, modelAr: "13" },
      { n: 2, modelAr: "n <= 1 (أ)" },
      { n: 3, modelAr: "O(n) (أ)" },
      { n: 4, modelAr: "O(log n) (أ)" },
      { n: 5, modelAr: "7" },
      { n: 6, modelAr: "خطأ" },
      { n: 7, modelAr: "'w' (أ)" },
      { n: 8, modelAr: "3" },
      { n: 9, modelAr: "صح" },
      { n: 10, modelAr: "O(n²) (أ)" },
    ],
  },
  "ws-day-09": {
    teacherDayRoute: "/teacher/day-09-answers",
    tasks: [
      { n: 1, modelAr: "120" },
      { n: 2, modelAr: "إيقاف التكرار (أ)" },
      { n: 3, modelAr: "21" },
      { n: 4, modelAr: "تشابه ذاتي (أ)" },
      { n: 5, modelAr: "12" },
      { n: 6, modelAr: "صح" },
      { n: 7, modelAr: "9" },
      { n: 8, modelAr: "استدعاء ذاتي + turtle (أ)" },
      { n: 9, modelAr: "صح" },
      { n: 10, modelAr: "48" },
    ],
  },
  "ws-day-10": {
    teacherDayRoute: "/teacher/day-10-answers",
    tasks: [
      { n: 1, modelAr: "class = قالب للكائنات (أ)" },
      { n: 2, modelAr: "25" },
      { n: 3, modelAr: "Teach" },
      { n: 4, modelAr: "OR البِتي (ب)" },
      { n: 5, modelAr: "7" },
      { n: 6, modelAr: "1,4,9" },
      { n: 7, modelAr: "1,4,6,4,1" },
      { n: 8, modelAr: "صح" },
      { n: 9, modelAr: "x = A() (ب)" },
      { n: 10, modelAr: "صح" },
    ],
  },
  "ws-day-11": {
    teacherDayRoute: "/teacher/day-11-answers",
    tasks: [
      { n: 1, modelAr: "التعلم من البيانات لاكتشاف الأنماط (أ)" },
      { n: 2, modelAr: "التدريب للتعلم والاختبار للقياس (أ)" },
      { n: 3, modelAr: "70" },
      { n: 4, modelAr: "توصيات المحتوى (أ)" },
      { n: 5, modelAr: "صح" },
      { n: 6, modelAr: "إخفاء الهوية (أ)" },
      { n: 7, modelAr: "خطأ" },
      { n: 8, modelAr: "مشكلة → حل → مثال → أثر (أ)" },
      { n: 9, modelAr: "3" },
      { n: 10, modelAr: "العدالة أو الخصوصية أو الشفافية" },
    ],
  },
  "ws-day-12": {
    teacherDayRoute: "/teacher/day-12-answers",
    tasks: [
      { n: 1, modelAr: "[01]*01 (أ)" },
      { n: 2, modelAr: "صح" },
      { n: 3, modelAr: "خطأ" },
      { n: 4, modelAr: "P (أ)" },
      { n: 5, modelAr: "صح" },
      { n: 6, modelAr: "10" },
      { n: 7, modelAr: "15" },
      { n: 8, modelAr: "عدد زوجي (أ)" },
      { n: 9, modelAr: "شبكات أو طرق أو صداقات أو جدولة" },
      { n: 10, modelAr: "صح" },
    ],
  },
  "ws-day-13": {
    teacherDayRoute: "/teacher/day-13-answers",
    tasks: [
      { n: 1, modelAr: "70" },
      { n: 2, modelAr: "صح" },
      { n: 3, modelAr: "30" },
      { n: 4, modelAr: "صح" },
      { n: 5, modelAr: "تعريف المشكلة (أ)" },
      { n: 6, modelAr: "صح" },
      { n: 7, modelAr: "عشوائي (ج)" },
      { n: 8, modelAr: "مثل: بايثون أو المنطق أو الخوارزميات" },
      { n: 9, modelAr: "مثل: طالب أو معلم أو فصل" },
      { n: 10, modelAr: "صح" },
    ],
  },
  "ws-day-14": {
    teacherDayRoute: "/teacher/day-14-answers",
    tasks: [
      { n: 1, modelAr: "75" },
      { n: 2, modelAr: "صح" },
      { n: 3, modelAr: "75" },
      { n: 4, modelAr: "صح" },
      { n: 5, modelAr: "المشكلة (أ)" },
      { n: 6, modelAr: "صح" },
      { n: 7, modelAr: "متابعة backlog يوميًا (أ)" },
      { n: 8, modelAr: "مثل: اختبار وظيفي أو تكامل أو واجهة" },
      { n: 9, modelAr: "مثل: تحسين التوقيت أو وضوح الشرح" },
      { n: 10, modelAr: "صح" },
    ],
  },
  "ws-day-15": {
    teacherDayRoute: "/teacher/day-15-answers",
    tasks: [
      { n: 1, modelAr: "4" },
      { n: 2, modelAr: "صح" },
      { n: 3, modelAr: "صح" },
      { n: 4, modelAr: "84" },
      { n: 5, modelAr: "الشرح جيد لكن يحتاج تبطيء في المقدمة (أ)" },
      { n: 6, modelAr: "صح" },
      { n: 7, modelAr: "بدون أي متابعة (ج)" },
      { n: 8, modelAr: "مثل: بايثون أو خوارزميات أو عرض" },
      { n: 9, modelAr: "مثل: مراجعة أسبوعية أو مشروع جديد" },
      { n: 10, modelAr: "خطأ" },
    ],
  },
};
