/**
 * Structured worksheet tasks — auto-gradable, no long free-text essays.
 * Legacy essay tasks without `type` fall back to textarea in the UI.
 */

const FB = {
  dec: "راجع القسمة المتكررة على 2 أو القيم المكانية.",
  bin: "راجع تحويل الثنائي: اجمع قوى 2 للخانات = 1.",
};

/** @type {Record<string, { tasks: object[] }>} */
export const STRUCTURED_WORKSHEETS = {
  "ws-day-01": {
    tasks: [
      {
        n: 1,
        type: "multi_part",
        pdfRef: "ص 77",
        textAr: "حوّل الأعداد التالية من النظام العشري إلى النظام الثنائي (6 خانات لكل رقم):",
        parts: [
          { id: "d2", type: "short_answer", promptAr: "2₁₀ → ثنائي", acceptedAnswers: ["000010", "10"], normalize: "binary", feedback: FB.dec },
          { id: "d11", type: "short_answer", promptAr: "11₁₀ → ثنائي", acceptedAnswers: ["001011", "1011"], normalize: "binary", feedback: FB.dec },
          { id: "d24", type: "short_answer", promptAr: "24₁₀ → ثنائي", acceptedAnswers: ["011000", "11000"], normalize: "binary", feedback: FB.dec },
          { id: "d50", type: "short_answer", promptAr: "50₁₀ → ثنائي", acceptedAnswers: ["110010"], normalize: "binary", feedback: FB.dec },
          { id: "d616", type: "short_answer", promptAr: "616₁₀ → ثنائي", acceptedAnswers: ["1001101000"], normalize: "binary", feedback: FB.dec },
          { id: "d22", type: "short_answer", promptAr: "22₁₀ → ثنائي", acceptedAnswers: ["010110", "10110"], normalize: "binary", feedback: FB.dec },
        ],
      },
      {
        n: 2,
        type: "multi_part",
        pdfRef: "ص 77",
        textAr: "حوّل الأعداد التالية من النظام الثنائي إلى العشري:",
        parts: [
          { id: "b1", type: "numeric_answer", promptAr: "101101₂ → عشري", acceptedAnswers: ["45"], normalize: "numeric", feedback: FB.bin },
          { id: "b2", type: "numeric_answer", promptAr: "111111₂ → عشري", acceptedAnswers: ["63"], normalize: "numeric", feedback: FB.bin },
          { id: "b3", type: "numeric_answer", promptAr: "00111011₂ → عشري", acceptedAnswers: ["59"], normalize: "numeric", feedback: FB.bin },
          { id: "b4", type: "numeric_answer", promptAr: "011010₂ → عشري", acceptedAnswers: ["26"], normalize: "numeric", feedback: FB.bin },
        ],
      },
      {
        n: 3,
        type: "short_answer",
        pdfRef: "ص 77",
        textAr: "ما القيمة العشرية للعدد الثنائي 1111111؟",
        acceptedAnswers: ["127"],
        normalize: "numeric",
        explanationAr: "1111111₂ = 64+32+16+8+4+2+1 = 127",
        feedback: { incorrect: FB.bin },
      },
      {
        n: 4,
        type: "multi_part",
        pdfRef: "ص 77",
        textAr: "أكمّل جدول التحويل — القيمة العشرية لكل عدد ثنائي:",
        parts: [
          { id: "t11", type: "numeric_answer", promptAr: "11₂", acceptedAnswers: ["3"], normalize: "numeric" },
          { id: "t111", type: "numeric_answer", promptAr: "111₂", acceptedAnswers: ["7"], normalize: "numeric" },
          { id: "t1111", type: "numeric_answer", promptAr: "1111₂", acceptedAnswers: ["15"], normalize: "numeric" },
          { id: "t11111", type: "numeric_answer", promptAr: "11111₂", acceptedAnswers: ["31"], normalize: "numeric" },
          { id: "t111111", type: "numeric_answer", promptAr: "111111₂", acceptedAnswers: ["63"], normalize: "numeric" },
        ],
      },
      {
        n: 5,
        type: "binary_cards_sheet",
        pdfRef: "ص 78–79",
        textAr: "بطاقات النظام الثنائي: مثّل الأعداد 12، 5، 16، 31 بقلب البطاقات (1، 2، 4، 8، 16).",
        cardValues: [16, 8, 4, 2, 1],
        targets: [12, 5, 16, 31],
        instructionAr: "اقلب البطاقات داخل المنصة — الظاهرة = 1، المخفية = 0.",
      },
      {
        n: 6,
        type: "multi_part",
        pdfRef: "ص 52–55",
        textAr: "الألوان RGB — اختر القيمة العشرية الصحيحة:",
        parts: [
          {
            id: "red",
            type: "multiple_choice",
            promptAr: "اللون الأحمر FF0000",
            choices: [
              { id: "a", textAr: "255" },
              { id: "b", textAr: "16777215" },
              { id: "c", textAr: "65280" },
              { id: "d", textAr: "65535" },
            ],
            correctAnswer: "b",
            explanationAr: "FF0000 = 255×256² = 16777215",
          },
          {
            id: "white",
            type: "multiple_choice",
            promptAr: "اللون الأبيض",
            choices: [
              { id: "a", textAr: "000000" },
              { id: "b", textAr: "FFFFFF" },
              { id: "c", textAr: "FF0000" },
              { id: "d", textAr: "00FF00" },
            ],
            correctAnswer: "b",
          },
          {
            id: "black",
            type: "multiple_choice",
            promptAr: "اللون الأسود",
            choices: [
              { id: "a", textAr: "000000" },
              { id: "b", textAr: "FFFFFF" },
              { id: "c", textAr: "808080" },
              { id: "d", textAr: "111111" },
            ],
            correctAnswer: "a",
          },
        ],
      },
      {
        n: 7,
        type: "multi_part",
        pdfRef: "ص 37–40",
        textAr: "ASCII و Unicode:",
        parts: [
          {
            id: "tf1",
            type: "true_false",
            promptAr: "Unicode يدعم تمثيل الحروف العربية.",
            correct: true,
            explanationAr: "Unicode يغطي معظم لغات العالم بما فيها العربية.",
          },
          {
            id: "mc1",
            type: "multiple_choice",
            promptAr: "أي ترميز يقتصر غالبًا على 128 حرفًا إنجليزيًا؟",
            choices: [
              { id: "a", textAr: "ASCII" },
              { id: "b", textAr: "Unicode" },
              { id: "c", textAr: "UTF-16 فقط" },
              { id: "d", textAr: "HTML" },
            ],
            correctAnswer: "a",
          },
        ],
      },
      {
        n: 8,
        type: "multi_part",
        pdfRef: "ص 14",
        textAr: "ميثاق الصف والتقويم القبلي:",
        parts: [
          {
            id: "charter",
            type: "multiple_choice",
            promptAr: "أي سلوك يتوافق مع ميثاق الصف الرقمي؟",
            choices: [
              { id: "a", textAr: "مشاركة كلمات المرور مع الزملاء" },
              { id: "b", textAr: "الاحترام والالتزام بقواعد الاستخدام المقبول" },
              { id: "c", textAr: "نسخ إجابات الآخرين دون إذن" },
              { id: "d", textAr: "إرسال روابط غير موثوقة" },
            ],
            correctAnswer: "b",
          },
          {
            id: "pre",
            type: "multiple_choice",
            promptAr: "لماذا التقويم القبلي مهم؟",
            choices: [
              { id: "a", textAr: "لمنع الطالب من بدء الدرس" },
              { id: "b", textAr: "تشخيصي — يساعد المعلم على دعم مستوى كل طالب" },
              { id: "c", textAr: "لتحديد رسوب الطالب نهائيًا" },
              { id: "d", textAr: "لا فائدة منه" },
            ],
            correctAnswer: "b",
          },
        ],
      },
    ],
  },
  "ws-day-02": {
    tasks: [
      {
        n: 1,
        type: "multi_part",
        pdfRef: "ص 93–96",
        textAr: "التحويلات — اكتب الناتج فقط:",
        parts: [
          { id: "bin", type: "numeric_answer", promptAr: "1010₂ → عشري", acceptedAnswers: ["10"], normalize: "numeric" },
          { id: "dec", type: "short_answer", promptAr: "25₁₀ → ثنائي", acceptedAnswers: ["11001"], normalize: "binary" },
          { id: "hex", type: "numeric_answer", promptAr: "A3₁₆ → عشري", acceptedAnswers: ["163"], normalize: "numeric" },
        ],
      },
      {
        n: 2,
        type: "multi_part",
        pdfRef: "ص 101",
        textAr: "حساب الأساس — اكتب ناتج الجمع:",
        parts: [
          { id: "badd", type: "short_answer", promptAr: "1011₂ + 1101₂ = (ثنائي)", acceptedAnswers: ["11000"], normalize: "binary" },
          { id: "padd", type: "short_answer", promptAr: "23₅ + 14₅ = (أساس 5)", acceptedAnswers: ["42"], normalize: "numeric" },
        ],
      },
      {
        n: 3,
        type: "multiple_choice",
        pdfRef: "ص 117",
        textAr: "أي وصف ينطبق على الخوارزمية الجيدة؟",
        choices: [
          { id: "a", textAr: "خطوات واضحة ومحددة قابلة للتنفيذ" },
          { id: "b", textAr: "جملة واحدة غامضة بدون ترتيب" },
          { id: "c", textAr: "كود بايثون فقط بدون شرح" },
          { id: "d", textAr: "نتيجة عشوائية" },
        ],
        correctAnswer: "a",
        explanationAr: "الخوارزمية = خطوات مرقمة واضحة من مدخلات إلى مخرجات.",
      },
      {
        n: 4,
        type: "true_false",
        pdfRef: "ص 115",
        textAr: "إذا كانت درجة الطالب 55، فالبرنامج if grade >= 50 يطبع «نجح».",
        correct: true,
        explanationAr: "55 ≥ 50 → الشرط صحيح.",
      },
      {
        n: 5,
        type: "multiple_choice",
        pdfRef: "ص 115",
        textAr: "أي تقدير يطبع البرنامج لدرجة 85؟",
        choices: [
          { id: "a", textAr: "ممتاز" },
          { id: "b", textAr: "جيد جداً" },
          { id: "c", textAr: "جيد" },
          { id: "d", textAr: "مقبول" },
        ],
        correctAnswer: "b",
        explanationAr: "85 ≥ 80 و < 90 → جيد جداً.",
      },
      {
        n: 6,
        type: "short_answer",
        pdfRef: "ص 126",
        textAr: "ما ناتج جمع الأعداد من 1 إلى 5 باستخدام while؟ (رقم فقط)",
        acceptedAnswers: ["15"],
        normalize: "numeric",
      },
      {
        n: 7,
        type: "numeric_answer",
        pdfRef: "ص 126",
        textAr: "ما مربع العدد 7؟ (ناتج for i in range(1,11) عند i=7)",
        acceptedAnswers: ["49"],
        normalize: "numeric",
      },
      {
        n: 8,
        type: "true_false",
        pdfRef: "ص 94–96",
        textAr: "0.1 + 0.2 قد لا يساوي بالضبط 0.3 في الحاسب بسبب تمثيل محدود للأعداد العائمة.",
        correct: true,
      },
      {
        n: 9,
        type: "multiple_choice",
        pdfRef: "ص 127",
        textAr: "ما وظيفة range في بايثون؟",
        choices: [
          { id: "a", textAr: "توليد تسلسل أعداد للتكرار" },
          { id: "b", textAr: "طباعة نص فقط" },
          { id: "c", textAr: "إيقاف البرنامج" },
          { id: "d", textAr: "تحويل ثنائي إلى عشري" },
        ],
        correctAnswer: "a",
      },
      {
        n: 10,
        type: "true_false",
        pdfRef: "ص 127",
        textAr: "يمكن استخدام if لاتخاذ قرار في برنامج بايثون.",
        correct: true,
      },
    ],
  },
  "ws-day-06": {
    tasks: [
      {
        n: 1,
        type: "short_answer",
        pdfRef: "ص 301–305",
        textAr: "شفّر الكلمة CAT بإزاحة قيصر = 2 (أحرف إنجليزية كبيرة)",
        acceptedAnswers: ["ECV"],
        explanationAr: "C→E، A→C، T→V",
      },
      {
        n: 2,
        type: "multiple_choice",
        pdfRef: "ص 307–310",
        textAr: "أي مكوّن الأسرع عادة؟",
        choices: [
          { id: "a", textAr: "Cache" },
          { id: "b", textAr: "RAM" },
          { id: "c", textAr: "HDD" },
          { id: "d", textAr: "USB خارجي" },
        ],
        correctAnswer: "a",
        explanationAr: "Cache الأقرب للمعالج.",
      },
      {
        n: 3,
        type: "multi_part",
        pdfRef: "ص 307–310",
        textAr: "طابِق المكوّن مع الوظيفة (اكتب الحرف فقط: أ، ب، ج):",
        parts: [
          {
            id: "cpu",
            type: "multiple_choice",
            promptAr: "CPU",
            choices: [
              { id: "a", textAr: "تنفيذ التعليمات" },
              { id: "b", textAr: "تخزين دائم" },
              { id: "c", textAr: "تسريع مؤقت فقط" },
            ],
            correctAnswer: "a",
          },
          {
            id: "ram",
            type: "multiple_choice",
            promptAr: "RAM",
            choices: [
              { id: "a", textAr: "تخزين أثناء التشغيل" },
              { id: "b", textAr: "طباعة" },
              { id: "c", textAr: "شبكة" },
            ],
            correctAnswer: "a",
          },
          {
            id: "hdd",
            type: "multiple_choice",
            promptAr: "HDD",
            choices: [
              { id: "a", textAr: "حفظ دائم" },
              { id: "b", textAr: "ذاكرة سريعة" },
              { id: "c", textAr: "معالجة" },
            ],
            correctAnswer: "a",
          },
        ],
      },
      {
        n: 4,
        type: "numeric_answer",
        pdfRef: "ص 312–314",
        textAr: "FCFS: P1(وصول 0، خدمة 3) و P2(وصول 1، خدمة 2) — ما انتظار P2؟",
        acceptedAnswers: ["2"],
        normalize: "numeric",
        explanationAr: "P2 يبدأ عند 3، وصوله 1 → انتظار 2.",
      },
      {
        n: 5,
        type: "true_false",
        pdfRef: "ص 313",
        textAr: "خوارزمية SRT تختار العملية ذات أقصر وقت متبقٍ على المعالج.",
        correct: true,
        explanationAr: "Shortest Remaining Time.",
      },
      {
        n: 6,
        type: "multiple_choice",
        pdfRef: "ص 295–338",
        textAr: "FCFS تعني:",
        choices: [
          { id: "a", textAr: "أول وصول أول خدمة" },
          { id: "b", textAr: "أقصر عملية أولاً دائمًا" },
          { id: "c", textAr: "عشوائي" },
          { id: "d", textAr: "بدون انتظار" },
        ],
        correctAnswer: "a",
      },
      {
        n: 7,
        type: "short_answer",
        pdfRef: "ص 301",
        textAr: "فك تشفير D بإزاحة 3 (حرف واحد)",
        acceptedAnswers: ["A"],
      },
      {
        n: 8,
        type: "true_false",
        pdfRef: "ص 322",
        textAr: "شفرة قيصر آمنة للرسائل السرية الحديثة.",
        correct: false,
        explanationAr: "سهلة الكسر — للتعلم فقط.",
      },
      {
        n: 9,
        type: "numeric_answer",
        pdfRef: "ص 314",
        textAr: "متوسط انتظار FCFS لـ P1(0,3) P2(1,2) P3(2,1) — قرّب لمنزلتين",
        acceptedAnswers: ["1.67", "1.7", "1.66"],
        normalize: "numeric",
        explanationAr: "(0+2+3)/3 ≈ 1.67",
      },
      {
        n: 10,
        type: "multiple_choice",
        pdfRef: "التقويم 6-ج",
        textAr: "وظيفة RAM الأساسية:",
        choices: [
          { id: "a", textAr: "تخزين البرامج والبيانات أثناء التشغيل" },
          { id: "b", textAr: "تنفيذ العمليات الحسابية فقط" },
          { id: "c", textAr: "حفظ دائم بعد الإطفاء" },
          { id: "d", textAr: "عرض الشاشة" },
        ],
        correctAnswer: "a",
      },
    ],
  },
  "ws-day-07": {
    tasks: [
      {
        n: 1,
        type: "short_answer",
        pdfRef: "ص 354",
        textAr: "x=10 و def f(): x=3; print(x) — ماذا تطبع f()؟",
        acceptedAnswers: ["3"],
        explanationAr: "x داخل f محلي يحجب x العام.",
      },
      {
        n: 2,
        type: "multiple_choice",
        pdfRef: "ص 354",
        textAr: "أول حرف في قاعدة LEGB يمثل:",
        choices: [
          { id: "a", textAr: "Local" },
          { id: "b", textAr: "Global" },
          { id: "c", textAr: "Built-in" },
          { id: "d", textAr: "Library" },
        ],
        correctAnswer: "a",
        explanationAr: "L = Local.",
      },
      {
        n: 3,
        type: "multiple_choice",
        pdfRef: "ص 370",
        textAr: "random.randint(1, 6) يعطي أعدادًا:",
        choices: [
          { id: "a", textAr: "من 1 إلى 6 شاملاً الطرفين" },
          { id: "b", textAr: "من 0 إلى 5" },
          { id: "c", textAr: "من 1 إلى 5" },
          { id: "d", textAr: "عشوائية عشرية فقط" },
        ],
        correctAnswer: "a",
      },
      {
        n: 4,
        type: "numeric_answer",
        pdfRef: "ص 370",
        textAr: "نردان: 4 و 3 — ما مجموعهما؟",
        acceptedAnswers: ["7"],
        normalize: "numeric",
      },
      {
        n: 5,
        type: "multiple_choice",
        pdfRef: "ص 370",
        textAr: "مجموع نردين = 7 — التصنيف:",
        choices: [
          { id: "a", textAr: "منخفض (≤6)" },
          { id: "b", textAr: "متوسط (7–9)" },
          { id: "c", textAr: "مرتفع (≥10)" },
          { id: "d", textAr: "تعادل" },
        ],
        correctAnswer: "b",
      },
      {
        n: 6,
        type: "numeric_answer",
        pdfRef: "ص 356",
        textAr: "كم خانة في لوحة تيك-تاك-تو 3×3؟",
        acceptedAnswers: ["9"],
        normalize: "numeric",
      },
      {
        n: 7,
        type: "numeric_answer",
        pdfRef: "ص 356",
        textAr: "كم خط فوز (صف+عمود+قطر) في تيك-تاك-تو؟",
        acceptedAnswers: ["8"],
        normalize: "numeric",
      },
      {
        n: 8,
        type: "true_false",
        pdfRef: "ص 356",
        textAr: "X في المواضع 0,1,2 (الصف العلوي) يفوز.",
        correct: true,
      },
      {
        n: 9,
        type: "multiple_choice",
        pdfRef: "ص 361",
        textAr: "أول مرحلة بناء لعبة برمجية:",
        choices: [
          { id: "a", textAr: "تخطيط القواعد" },
          { id: "b", textAr: "كتابة الواجهة مباشرة" },
          { id: "c", textAr: "العرض Demo" },
          { id: "d", textAr: "حذف الاختبارات" },
        ],
        correctAnswer: "a",
      },
      {
        n: 10,
        type: "true_false",
        pdfRef: "ص 361–362",
        textAr: "pseudocode يُكتب قبل كود بايثون النهائي.",
        correct: true,
      },
    ],
  },
  "ws-day-08": {
    tasks: [
      {
        n: 1,
        type: "numeric_answer",
        pdfRef: "ص 392",
        textAr: "F(7) في متتالية فيبوناتشي (F(0)=0, F(1)=1)؟",
        acceptedAnswers: ["13"],
        normalize: "numeric",
      },
      {
        n: 2,
        type: "multiple_choice",
        pdfRef: "ص 392",
        textAr: "الحالة الأساسية في fib_recursive(n) عادة:",
        choices: [
          { id: "a", textAr: "n <= 1" },
          { id: "b", textAr: "n == 10" },
          { id: "c", textAr: "while True" },
          { id: "d", textAr: "لا حاجة" },
        ],
        correctAnswer: "a",
      },
      {
        n: 3,
        type: "multiple_choice",
        pdfRef: "ص 384",
        textAr: "for i in range(n): ... — Big-O؟",
        choices: [
          { id: "a", textAr: "O(n)" },
          { id: "b", textAr: "O(1)" },
          { id: "c", textAr: "O(n²)" },
          { id: "d", textAr: "O(log n)" },
        ],
        correctAnswer: "a",
      },
      {
        n: 4,
        type: "multiple_choice",
        pdfRef: "ص 384",
        textAr: "Binary Search على قائمة مرتبة — التعقيد؟",
        choices: [
          { id: "a", textAr: "O(log n)" },
          { id: "b", textAr: "O(n²)" },
          { id: "c", textAr: "O(1)" },
          { id: "d", textAr: "O(2^n)" },
        ],
        correctAnswer: "a",
      },
      {
        n: 5,
        type: "numeric_answer",
        pdfRef: "ص 395",
        textAr: "3 أقراص في برج هانوي — أقل عدد حركات (2^n−1)؟",
        acceptedAnswers: ["7"],
        normalize: "numeric",
      },
      {
        n: 6,
        type: "true_false",
        pdfRef: "ص 395",
        textAr: "في هانوي يُسمح بوضع قرص أكبر فوق قرص أصغر.",
        correct: false,
      },
      {
        n: 7,
        type: "multiple_choice",
        pdfRef: "ص 399",
        textAr: "كتابة ملف جديد (مسح المحتوى القديم) — الوضع:",
        choices: [
          { id: "a", textAr: "'w'" },
          { id: "b", textAr: "'r'" },
          { id: "c", textAr: "'x'" },
          { id: "d", textAr: "'rb'" },
        ],
        correctAnswer: "a",
      },
      {
        n: 8,
        type: "numeric_answer",
        pdfRef: "ص 399",
        textAr: "محتوى 'a\\nb\\nc' — كم سطر؟",
        acceptedAnswers: ["3"],
        normalize: "numeric",
      },
      {
        n: 9,
        type: "true_false",
        pdfRef: "ص 399",
        textAr: "with open(...) as f: يغلق الملف تلقائيًا عند الخروج.",
        correct: true,
      },
      {
        n: 10,
        type: "multiple_choice",
        pdfRef: "ص 396",
        textAr: "Selection Sort — التعقيد الزمني النموذجي:",
        choices: [
          { id: "a", textAr: "O(n²)" },
          { id: "b", textAr: "O(n)" },
          { id: "c", textAr: "O(log n)" },
          { id: "d", textAr: "O(1)" },
        ],
        correctAnswer: "a",
      },
    ],
  },
  "ws-day-09": {
    tasks: [
      {
        n: 1,
        type: "numeric_answer",
        pdfRef: "ص 407",
        textAr: "factorial(5) = ?",
        acceptedAnswers: ["120"],
        normalize: "numeric",
      },
      {
        n: 2,
        type: "multiple_choice",
        pdfRef: "ص 405",
        textAr: "الحالة الأساسية في دالة متكررة ضرورية لـ:",
        choices: [
          { id: "a", textAr: "إيقاف التكرار" },
          { id: "b", textAr: "تسريع الإنترنت" },
          { id: "c", textAr: "حذف المتغيرات" },
          { id: "d", textAr: "لا فائدة" },
        ],
        correctAnswer: "a",
      },
      {
        n: 3,
        type: "numeric_answer",
        pdfRef: "ص 409",
        textAr: "sumToN(6) = ?",
        acceptedAnswers: ["21"],
        normalize: "numeric",
      },
      {
        n: 4,
        type: "multiple_choice",
        pdfRef: "ص 415",
        textAr: "الكسورية تتميز بـ:",
        choices: [
          { id: "a", textAr: "تشابه ذاتي — الجزء يشبه الكل" },
          { id: "b", textAr: "خط مستقيم واحد" },
          { id: "c", textAr: "عدم التكرار" },
          { id: "d", textAr: "ملف CSV" },
        ],
        correctAnswer: "a",
      },
      {
        n: 5,
        type: "numeric_answer",
        pdfRef: "ص 417",
        textAr: "ندفة Koch — 3 أضلاع، عمق 1 — كم قطعة خط؟",
        acceptedAnswers: ["12"],
        normalize: "numeric",
      },
      {
        n: 6,
        type: "true_false",
        pdfRef: "ص 417",
        textAr: "منحنى Koch يستبدل كل قطعة بأربع قطع أقصر.",
        correct: true,
      },
      {
        n: 7,
        type: "numeric_answer",
        pdfRef: "ص 418",
        textAr: "مثلث Sierpinski — عمق 2 — كم مثلثًا صغيرًا؟",
        acceptedAnswers: ["9"],
        normalize: "numeric",
      },
      {
        n: 8,
        type: "multiple_choice",
        pdfRef: "ص 418",
        textAr: "رسم Sierpinski يستخدم غالبًا:",
        choices: [
          { id: "a", textAr: "استدعاء ذاتي + turtle" },
          { id: "b", textAr: "SQL فقط" },
          { id: "c", textAr: "HTML فقط" },
          { id: "d", textAr: "لا حلقات ولا دوال" },
        ],
        correctAnswer: "a",
      },
      {
        n: 9,
        type: "true_false",
        pdfRef: "ص 410",
        textAr: "RecursionError يحدث عند غياب حالة أساس مناسبة.",
        correct: true,
      },
      {
        n: 10,
        type: "numeric_answer",
        pdfRef: "ص 417",
        textAr: "3 أضلاع، عمق 2 — كم قطعة خط في Koch؟",
        acceptedAnswers: ["48"],
        normalize: "numeric",
      },
    ],
  },
  "ws-day-10": {
    tasks: [
      {
        n: 1,
        type: "multiple_choice",
        pdfRef: "ص 423",
        textAr: "في OOP، الـ class تمثل:",
        choices: [
          { id: "a", textAr: "قالبًا للكائنات" },
          { id: "b", textAr: "كائنًا منفردًا فقط" },
          { id: "c", textAr: "نوع حلقة" },
          { id: "d", textAr: "ملف نصي" },
        ],
        correctAnswer: "a",
      },
      {
        n: 2,
        type: "numeric_answer",
        pdfRef: "ص 425",
        textAr: "مساحة مربع ضلعه 5؟",
        acceptedAnswers: ["25"],
        normalize: "numeric",
      },
      {
        n: 3,
        type: "short_answer",
        pdfRef: "ص 437",
        textAr: "فك البتات 01010100 01100101 01100001 01100011 01101000 00000000",
        acceptedAnswers: ["Teach", "teach"],
      },
      {
        n: 4,
        type: "multiple_choice",
        pdfRef: "ص 439",
        textAr: "العامل المستخدم في المثال x |= y هو:",
        choices: [
          { id: "a", textAr: "AND" },
          { id: "b", textAr: "OR البِتي" },
          { id: "c", textAr: "==" },
          { id: "d", textAr: "!=" },
        ],
        correctAnswer: "b",
      },
      {
        n: 5,
        type: "numeric_answer",
        pdfRef: "ص 441",
        textAr: "شجرة متكررة بعمق 2 — عدد القطع التقريبي؟",
        acceptedAnswers: ["7"],
        normalize: "numeric",
      },
      {
        n: 6,
        type: "short_answer",
        pdfRef: "ص 468",
        textAr: "حتى 10 خزائن — اكتب أرقام الخزائن المفتوحة (مفصولة بفواصل)",
        acceptedAnswers: ["1,4,9", "1-4-9"],
      },
      {
        n: 7,
        type: "short_answer",
        pdfRef: "ص 468",
        textAr: "صف مثلث باسكال رقم 4",
        acceptedAnswers: ["1,4,6,4,1", "1-4-6-4-1"],
      },
      {
        n: 8,
        type: "true_false",
        pdfRef: "ص 468",
        textAr: "الخزائن التي تبقى مفتوحة هي ذات الأرقام المربعة الكاملة.",
        correct: true,
      },
      {
        n: 9,
        type: "multiple_choice",
        pdfRef: "ص 421",
        textAr: "أي تعليمة تنشئ كائنًا من class A؟",
        choices: [
          { id: "a", textAr: "class A(object)" },
          { id: "b", textAr: "x = A()" },
          { id: "c", textAr: "def A()" },
          { id: "d", textAr: "import A" },
        ],
        correctAnswer: "b",
      },
      {
        n: 10,
        type: "true_false",
        pdfRef: "ص 441",
        textAr: "غياب base case في رسم الشجرة المتكررة قد يسبب تكرارًا لا نهائيًا.",
        correct: true,
      },
    ],
  },
  "ws-day-11": {
    tasks: [
      {
        n: 1,
        type: "multiple_choice",
        pdfRef: "day11",
        textAr: "أي تعريف أدق للذكاء الاصطناعي؟",
        choices: [
          { id: "a", textAr: "التعلم من البيانات لاكتشاف الأنماط" },
          { id: "b", textAr: "برمجة if ثابتة فقط" },
          { id: "c", textAr: "رسم شرائح فقط" },
          { id: "d", textAr: "تخزين ملفات فقط" },
        ],
        correctAnswer: "a",
      },
      {
        n: 2,
        type: "multiple_choice",
        pdfRef: "day11",
        textAr: "الفرق الصحيح بين training و test data:",
        choices: [
          { id: "a", textAr: "التدريب للتعلم والاختبار للقياس" },
          { id: "b", textAr: "كلاهما نفس الشيء" },
          { id: "c", textAr: "الاختبار للتعلم فقط" },
          { id: "d", textAr: "لا نحتاج اختبار" },
        ],
        correctAnswer: "a",
      },
      {
        n: 3,
        type: "numeric_answer",
        pdfRef: "day11",
        textAr: "TP=8, TN=6, FP=2, FN=4 — الدقة (%)؟",
        acceptedAnswers: ["70"],
        normalize: "numeric",
      },
      {
        n: 4,
        type: "multiple_choice",
        pdfRef: "day11",
        textAr: "أي مثال يعد تطبيقًا للذكاء الاصطناعي؟",
        choices: [
          { id: "a", textAr: "توصيات المحتوى" },
          { id: "b", textAr: "زر إيقاف التشغيل" },
          { id: "c", textAr: "كابل USB" },
          { id: "d", textAr: "مجلد فارغ" },
        ],
        correctAnswer: "a",
      },
      {
        n: 5,
        type: "true_false",
        pdfRef: "day11",
        textAr: "انحياز البيانات قد يؤدي لقرارات غير عادلة.",
        correct: true,
      },
      {
        n: 6,
        type: "multiple_choice",
        pdfRef: "day11",
        textAr: "الإجراء الأنسب لحماية الخصوصية في بيانات الطلاب:",
        choices: [
          { id: "a", textAr: "إخفاء الهوية" },
          { id: "b", textAr: "نشر الأسماء كاملة" },
          { id: "c", textAr: "مشاركة كلمات المرور" },
          { id: "d", textAr: "إيقاف التشفير" },
        ],
        correctAnswer: "a",
      },
      {
        n: 7,
        type: "true_false",
        pdfRef: "day11",
        textAr: "يمكن اعتبار الدقة وحدها دائمًا كافية للحكم على النموذج.",
        correct: false,
      },
      {
        n: 8,
        type: "multiple_choice",
        pdfRef: "day11",
        textAr: "أفضل ترتيب مبسط لعرض بحث AI:",
        choices: [
          { id: "a", textAr: "مشكلة → حل → مثال → أثر" },
          { id: "b", textAr: "أثر → مثال → عنوان" },
          { id: "c", textAr: "خاتمة فقط" },
          { id: "d", textAr: "صور بدون شرح" },
        ],
        correctAnswer: "a",
      },
      {
        n: 9,
        type: "numeric_answer",
        pdfRef: "day11",
        textAr: "العدد الموصى به تقريبًا للنقاط في الشريحة الواحدة:",
        acceptedAnswers: ["3"],
        normalize: "numeric",
      },
      {
        n: 10,
        type: "short_answer",
        pdfRef: "day11",
        textAr: "اذكر قيمة أخلاقية أساسية في استخدام AI",
        acceptedAnswers: ["العدالة", "الخصوصية", "الشفافية"],
      },
    ],
  },
  "ws-day-12": {
    tasks: [
      {
        n: 1,
        type: "multiple_choice",
        pdfRef: "day12",
        textAr: "Regex الصحيح لسلاسل ثنائية تنتهي بـ 01:",
        choices: [
          { id: "a", textAr: "[01]*01" },
          { id: "b", textAr: "01*[01]" },
          { id: "c", textAr: "[01]+10" },
          { id: "d", textAr: "0*1*" },
        ],
        correctAnswer: "a",
      },
      {
        n: 2,
        type: "true_false",
        pdfRef: "day12",
        textAr: "في DFA يوجد انتقال وحيد لكل رمز من كل حالة.",
        correct: true,
      },
      {
        n: 3,
        type: "true_false",
        pdfRef: "day12",
        textAr: "NFA لا يمكن تحويله إلى DFA.",
        correct: false,
      },
      {
        n: 4,
        type: "multiple_choice",
        pdfRef: "day12",
        textAr: "الفرز التقليدي يُصنف غالبًا ضمن:",
        choices: [
          { id: "a", textAr: "P" },
          { id: "b", textAr: "NP فقط" },
          { id: "c", textAr: "غير قابل للحل" },
          { id: "d", textAr: "لا شيء مما سبق" },
        ],
        correctAnswer: "a",
      },
      {
        n: 5,
        type: "true_false",
        pdfRef: "day12",
        textAr: "كل مسائل P ضمن NP.",
        correct: true,
      },
      {
        n: 6,
        type: "numeric_answer",
        pdfRef: "day12",
        textAr: "عدد الحواف في الرسم الكامل K5:",
        acceptedAnswers: ["10"],
        normalize: "numeric",
      },
      {
        n: 7,
        type: "numeric_answer",
        pdfRef: "day12",
        textAr: "عدد الحواف في K6:",
        acceptedAnswers: ["15"],
        normalize: "numeric",
      },
      {
        n: 8,
        type: "multiple_choice",
        pdfRef: "day12",
        textAr: "مجموع درجات رؤوس رسم غير موجه يكون دائمًا:",
        choices: [
          { id: "a", textAr: "عددًا زوجيًا" },
          { id: "b", textAr: "عددًا فرديًا" },
          { id: "c", textAr: "صفر دائمًا" },
          { id: "d", textAr: "عددًا أوليًا" },
        ],
        correctAnswer: "a",
      },
      {
        n: 9,
        type: "short_answer",
        pdfRef: "day12",
        textAr: "اذكر تطبيقًا واحدًا لنظرية المخططات",
        acceptedAnswers: ["شبكات", "طرق", "صداقات", "جدولة"],
      },
      {
        n: 10,
        type: "true_false",
        pdfRef: "day12",
        textAr: "السلسلة 1101 تنتهي بـ 01.",
        correct: true,
      },
    ],
  },
  "ws-day-13": {
    tasks: [
      {
        n: 1,
        type: "numeric_answer",
        pdfRef: "day13",
        textAr: "متوسط [60, 70, 80] = ؟",
        acceptedAnswers: ["70"],
        normalize: "numeric",
      },
      {
        n: 2,
        type: "true_false",
        pdfRef: "day13",
        textAr: "المراجعة المنتظمة تساعد قبل التقويم البعدي.",
        correct: true,
      },
      {
        n: 3,
        type: "numeric_answer",
        pdfRef: "day13",
        textAr: "Pre=50 و Post=65 — نسبة التحسن %؟",
        acceptedAnswers: ["30"],
        normalize: "numeric",
      },
      {
        n: 4,
        type: "true_false",
        pdfRef: "day13",
        textAr: "quiz-post يُستخدم لقياس التقدم بعد التعلم.",
        correct: true,
      },
      {
        n: 5,
        type: "multiple_choice",
        pdfRef: "day13",
        textAr: "الخطوة الأولى في المشروع النهائي:",
        choices: [
          { id: "a", textAr: "تعريف المشكلة" },
          { id: "b", textAr: "كتابة العرض فقط" },
          { id: "c", textAr: "اختيار لون الواجهة" },
          { id: "d", textAr: "نشر المشروع فورًا" },
        ],
        correctAnswer: "a",
      },
      {
        n: 6,
        type: "true_false",
        pdfRef: "day13",
        textAr: "الهدف: (رفع دقة النموذج إلى 80% خلال أسبوع) هدف SMART.",
        correct: true,
      },
      {
        n: 7,
        type: "multiple_choice",
        pdfRef: "day13",
        textAr: "أي عنصر ليس من SMART؟",
        choices: [
          { id: "a", textAr: "قابل للقياس" },
          { id: "b", textAr: "مؤطر زمنيًا" },
          { id: "c", textAr: "عشوائي" },
          { id: "d", textAr: "واقعي" },
        ],
        correctAnswer: "c",
      },
      {
        n: 8,
        type: "short_answer",
        pdfRef: "day13",
        textAr: "اذكر محورًا دراسيًا يحتاج تقوية",
        acceptedAnswers: ["بايثون", "منطق", "خوارزميات", "أنظمة الأعداد"],
      },
      {
        n: 9,
        type: "short_answer",
        pdfRef: "day13",
        textAr: "اذكر مستخدمًا مستهدفًا لمشروعك",
        acceptedAnswers: ["طالب", "معلم", "مدرسة", "فصل"],
      },
      {
        n: 10,
        type: "true_false",
        pdfRef: "day13",
        textAr: "خطة المشروع يجب أن تشمل مهامًا ومواعيد واضحة.",
        correct: true,
      },
    ],
  },
  "ws-day-14": {
    tasks: [
      {
        n: 1,
        type: "numeric_answer",
        pdfRef: "day14",
        textAr: "أنجزت 6 مهام من أصل 8 — نسبة الإنجاز %؟",
        acceptedAnswers: ["75"],
        normalize: "numeric",
      },
      {
        n: 2,
        type: "true_false",
        pdfRef: "day14",
        textAr: "تقسيم المشروع إلى وحدات يساعد على تقليل التعقيد.",
        correct: true,
      },
      {
        n: 3,
        type: "numeric_answer",
        pdfRef: "day14",
        textAr: "نجح 9 اختبارات من 12 — pass rate %؟",
        acceptedAnswers: ["75"],
        normalize: "numeric",
      },
      {
        n: 4,
        type: "true_false",
        pdfRef: "day14",
        textAr: "إعادة إنتاج الخطأ خطوة أولى جيدة قبل الإصلاح.",
        correct: true,
      },
      {
        n: 5,
        type: "multiple_choice",
        pdfRef: "day14",
        textAr: "الجزء الأول في العرض التقديمي:",
        choices: [
          { id: "a", textAr: "المشكلة" },
          { id: "b", textAr: "الكود الكامل" },
          { id: "c", textAr: "الخاتمة" },
          { id: "d", textAr: "الأسئلة" },
        ],
        correctAnswer: "a",
      },
      {
        n: 6,
        type: "true_false",
        pdfRef: "day14",
        textAr: "يجب تقديم demo حي قبل الخاتمة.",
        correct: true,
      },
      {
        n: 7,
        type: "multiple_choice",
        pdfRef: "day14",
        textAr: "أي ممارسة أفضل في sprint؟",
        choices: [
          { id: "a", textAr: "متابعة backlog يوميًا" },
          { id: "b", textAr: "العمل بلا خطة" },
          { id: "c", textAr: "دمج كل شيء آخر يوم" },
          { id: "d", textAr: "تجاهل الاختبارات" },
        ],
        correctAnswer: "a",
      },
      {
        n: 8,
        type: "short_answer",
        pdfRef: "day14",
        textAr: "اذكر نوع اختبار مناسب لمشروعك",
        acceptedAnswers: ["وظيفي", "تكامل", "واجهة", "أداء"],
      },
      {
        n: 9,
        type: "short_answer",
        pdfRef: "day14",
        textAr: "اذكر مخرجًا واحدًا للبروفة النهائية",
        acceptedAnswers: ["تحسين التوقيت", "وضوح الشرح", "ترتيب الشرائح"],
      },
      {
        n: 10,
        type: "true_false",
        pdfRef: "day14",
        textAr: "تقرير الاختبارات جزء مهم قبل العرض النهائي.",
        correct: true,
      },
    ],
  },
  "ws-day-15": {
    tasks: [
      {
        n: 1,
        type: "numeric_answer",
        pdfRef: "day15",
        textAr: "متوسط rubric [4,5,4,3] = ؟",
        acceptedAnswers: ["4"],
        normalize: "numeric",
      },
      {
        n: 2,
        type: "true_false",
        pdfRef: "day15",
        textAr: "العرض النهائي يبدأ بالمشكلة قبل الحل.",
        correct: true,
      },
      {
        n: 3,
        type: "true_false",
        pdfRef: "day15",
        textAr: "التغذية الراجعة الفعالة يجب أن تكون محددة.",
        correct: true,
      },
      {
        n: 4,
        type: "numeric_answer",
        pdfRef: "day15",
        textAr: "42 من 50 تساوي تقريبًا كم %؟",
        acceptedAnswers: ["84"],
        normalize: "numeric",
      },
      {
        n: 5,
        type: "multiple_choice",
        pdfRef: "day15",
        textAr: "أي ملاحظة هي الأكثر بنائية؟",
        choices: [
          { id: "a", textAr: "الشرح جيد لكن يحتاج تبطيء في المقدمة" },
          { id: "b", textAr: "العرض ضعيف جدًا" },
          { id: "c", textAr: "لا تعليق" },
          { id: "d", textAr: "كرر نفس العرض" },
        ],
        correctAnswer: "a",
      },
      {
        n: 6,
        type: "true_false",
        pdfRef: "day15",
        textAr: "النتيجة النهائية تساعد في تحديد خطوة التعلم القادمة.",
        correct: true,
      },
      {
        n: 7,
        type: "multiple_choice",
        pdfRef: "day15",
        textAr: "العنصر غير المناسب لخطة ما بعد الدورة:",
        choices: [
          { id: "a", textAr: "هدف قابل للقياس" },
          { id: "b", textAr: "موعد زمني" },
          { id: "c", textAr: "بدون أي متابعة" },
          { id: "d", textAr: "مؤشر تقدم" },
        ],
        correctAnswer: "c",
      },
      {
        n: 8,
        type: "short_answer",
        pdfRef: "day15",
        textAr: "اذكر مهارة واحدة اكتسبتها في الدورة",
        acceptedAnswers: ["بايثون", "خوارزميات", "منطق", "عرض", "اختبار"],
      },
      {
        n: 9,
        type: "short_answer",
        pdfRef: "day15",
        textAr: "اذكر خطوة واحدة لما بعد الدورة",
        acceptedAnswers: ["مشروع جديد", "مراجعة أسبوعية", "تعلم متقدم", "خطة شهرية"],
      },
      {
        n: 10,
        type: "true_false",
        pdfRef: "day15",
        textAr: "نهاية الدورة تعني نهاية التعلم.",
        correct: false,
      },
    ],
  },
};

export function getStructuredTasks(worksheetId) {
  return STRUCTURED_WORKSHEETS[worksheetId]?.tasks ?? null;
}
